// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXqb-3axqCv0L1zAkIL39B0rzv_E9IqC4',
    appId: '1:948635781738:android:7e1018ea1ace4849f15813',
    messagingSenderId: '948635781738',
    projectId: 'docmanager-4cedb',
    storageBucket: 'docmanager-4cedb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4JRnCN8LmFvy8EY2dcWRxdqOqMlWnxoA',
    appId: '1:948635781738:ios:eee455a13e0e1e4af15813',
    messagingSenderId: '948635781738',
    projectId: 'docmanager-4cedb',
    storageBucket: 'docmanager-4cedb.appspot.com',
    androidClientId: '948635781738-o2b8p7k32tueelp2chd5dcefqe099ach.apps.googleusercontent.com',
    iosClientId: '948635781738-6mu0usskqcbuk28381a8l0don8v3fbqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.docManager',
  );
}
